version = 0.1
[default.pipeline_bootstrap.parameters]
oidc_provider_url = "https://token.actions.githubusercontent.com"
oidc_client_id = "sts.amazonaws.com"
github_org = "pthungathurthi"
github_repo = "OrderServiceFunction"
deployment_branch = "master"
oidc_provider = "github-actions"
permissions_provider = "OpenID Connect (OIDC)"

[test.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::183295410578:role/aws-sam-cli-managed-test-pipe-PipelineExecutionRole-VkYvol2Wt0Ko"
cloudformation_execution_role = "arn:aws:iam::183295410578:role/aws-sam-cli-managed-test--CloudFormationExecutionRo-tPro3OdmguIG"
artifacts_bucket = "aws-sam-cli-managed-test-pipeline--artifactsbucket-nnszw19am9xj"
image_repository = ""
region = "ap-southeast-2"
